apiVersion: batch/v1
kind: CronJob
metadata:
  name: { include "jimmeapp.fullname" . }-cron
spec:
  schedule: "{{ .Values.cron.schedule }}"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: cron
              image: "{{ .Values.cron.image.repository }}:{{ .Values.cron.image.tag }}"
              imagePullPolicy: {{ .Values.cron.image.pullPolicy }}
          restartPolicy: OnFailure