name: Build, Push, and Deploy

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build and push Web API image
        run: |
          docker build -t ghcr.io/pascalicatt/jimmeapp.webapi:latest -f JimmeApp.WebApi/Dockerfile .
          docker push ghcr.io/pascalicatt/jimmeapp.webapi:latest

      - name: Build and push CronJob image
        run: |
          docker build -t ghcr.io/pascalicatt/jimmeapp.cronjob:latest -f JimmeApp.CronJob/Dockerfile .
          docker push ghcr.io/pascalicatt/jimmeapp.cronjob:latest

      - name: Release Helm Chart
        uses: helm/chart-releaser-action@v1.7.0
        with:
          skip_existing: true
        env:
          CR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
